### ISSUE TITLE
SMTP allow_from_override

### ISSUE THREAD

**Issue by coolibre** [tiredofit/docker-alpine#66]
**Description of the feature**

implement SMTP allow_from_override

**Benftits of feature**

In my freescout environment I need this to login with one technical smtp user and let the "from" be whatever mailbox address.
Setting "allow_from_override off" in /etc/msmtprc enables this usecase for my setup. Otherwise I get errors that from doesnt match my login name for smtp.

**Additional context**

**Comment by tiredofit** [comment]
I can support this. Thanks for the work.

**Comment by tiredofit** [comment]
Tagged as `7.8.7` - It takes a couple hours for all the images to build, but I will force a manual build of the downstream images since you had mentioned freescout. This will build new `:latests` of:

- `tiredofit/nginx`
- `tiredofit/nginx-php-fpm`
- `tiredofit/freescout`

Realistically it will be about 8 hours depending on how fast I remember to trigger the next manual builds.

**Comment by tiredofit** [comment]
All have been `:latest` images have been rebuilt. We'll have to wait until a new release for Freescout upstream occurs until a tagged release will come... Thanks again.
